In [3]:
import pandas as pd
import numpy as np

In [4]:
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Problem 1 - Calculation by Hand

#### Calculation by hand<br>

$$A =\begin{bmatrix}-1 & 2 & 3\\
4 & -5 & 6\\7 & 8 & -9\end{bmatrix}$$,$$B =\begin{bmatrix}0 & 2 & 1\\0 & 2 & -8\\2 & 9 & -1\end{bmatrix}$$,
$$AB =\begin{bmatrix}0+0+6 & -2+4+27 & -1+(-16)+(-3)\\0+0+12 & 8+(-10)+54 & 4+40+(-6)\\0+0+(-18) & 14+16+(-81) & 7+(-64)+(-9)\end{bmatrix}$$,$$AB =\begin{bmatrix}6 & 29 & -20\\12 & 52 & 38\\-18 & -51 & -48\end{bmatrix}$$

# Problem 2 - Calculation by NumPy function

### Method-1

In [12]:
np.matmul(A,B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### Method-2

In [13]:
np.dot(A,B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### Method-3

In [14]:
A@B

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### Scratch implementation of matrix product

In [15]:
A

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [16]:
B

array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

In [6]:
# Initializing a 3x3 result matrix 
result = [[0,0,0], 
        [0,0,0], 
        [0,0,0]] 
  
# Iterate each row of A 
for i in range(len(A)): 
  
    # Iterate each column of B 
    for j in range(len(B[0])): 

        # Iterate each row of B 
        for k in range(len(B)): 
            result[i][j] += A[i][k] * B[k][j] 

for r in result: 
    print(r)

[6, 29, -20]
[12, 52, 38]
[-18, -51, -48]


# Problem 3 - Implementation of calculation of a certain element

Multiply the (0,0) element $a_{0, 0}$ of matrix A with the (0,0) element $b_{0, 0}$ of matrix B

In [7]:
ab = A[0][0] * B[0][0]
ab

0

In [8]:
a1b1 = A[0][1] * B[1][0]
a1b1

0

In [9]:
a2b2 = A[0][2] * B[2][0]
a2b2

6

In [11]:
total = ab + a1b1 + a2b2
total

6

# Problem 4 Creating a function that performs matrix multiplication


In [12]:
np.empty(3*3)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [ ]:
def product_of_matrix(A, B):
    # Initializing a 3x3 result matrix 
    result = np.empty

    # Iterate each row of A 
    for i in range(len(A)): 

        # Iterate each column of B 
        for j in range(len(B[0])): 

            # Iterate each row of B 
            for k in range(len(B)): 
                result[i][j] += A[i][k] * B[k][j] 

# Problem 5 Judge the input whose calculation is not defined

In [26]:
def product_of_matrix (d,e):
    matrix_de = np.empty([3,3])
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
if d.shape[0] -- e.shape[1]:
    print(product_of_matrix(d,e))
else:
    print("matrices are not aligned")


None


# [Problem 6] Transposition

In [14]:
A

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [13]:
A.T

array([[-1,  4,  7],
       [ 2, -5,  8],
       [ 3,  6, -9]])

In [15]:
A.transpose()

array([[-1,  4,  7],
       [ 2, -5,  8],
       [ 3,  6, -9]])